### ISSUE TITLE
Deploy as cf app

### ISSUE THREAD

**Issue by PvanHengel** [cloudfoundry-incubator/admin-ui#145]
Hi has anyone done any work to deply the admin ui as an app within the cloud foundry instance or must it be installed as stand alone?

**Comment by rboykin** [comment]
Just tried it on cf_nise_installer image and mostly got it to function.  Items of interest:
* I updated my config/default.yml.  This includes the ccdb_uri, cloud_controller_uri, mbus and uaadb_uri
* I modified lib/admin/config.rb to return the port as ENV['VCAP_APP_PORT'] || @config[:port]
* I modified /var/vcap/jobs/dea_next/config/warden.yml network.allow_host_access to be true
* I modified /var/vcap/jobs/haproxy/config/haproxy.conf global/tune.bufsize to be larger to accommodate the large request URL's  due to use of DataTables on the Admin UI JavaScript side.  I increased on my local installation from 16384 to 32768
* Realize the stats regular collecting won't be persisted across restarts since the sqlite DB is created local to the application.  I didn't try to tie this in to a separate service.
* I pushed with cf push adminui -c "ruby bin/admin"
* You can then look at the adminui log file with cf files adminui app/admin_ui.log
* You can hit similarly to any other app:  https://adminui.<your domain>

**Comment by PvanHengel** [comment]
Awesome this works like a charm, we should update the docs to include this I think its very helpful!
