### ISSUE TITLE
Getting csv files fail

### ISSUE THREAD

**Issue by MNitta** [cloudfoundry-incubator/admin-ui#158]
After long-running admin-ui, getting a csv file from admin-ui fails. I have attached a snippet of admin_ui.log file.
[admin_ui.log.txt](https://github.com/cloudfoundry-incubator/admin-ui/files/318177/admin_ui.log.txt)

It seems that NATS discovery failed and after that, getting a csv file always fail (size is 0). I am using a bit old version (commit id: 75853b56ba4afd11eea1d1d89d06b627b1f68bfd (corresponding to a commit made on  Nov 19, 2015).

**Comment by rboykin** [comment]
@MNitta Since the commit you reference, I have moved up through four iterations of the DataTables Buttons JavaScript library where the CSV function is supported.  

Can you further define how getting a csv file from admin-ui fails?  Are you meaning the Save/CSV operation or the Download operation?

Also, it might be interesting for you to turn on your javascript console within your browser to see if any errors appear there when this fails.

Lastly, can you please try with the latest version of the Admin UI and see if this still occurs?

I have run the latest Admin UI against cf release 237 intentionally configuring the NATS connection incorrectly and I cannot recreate your lack of CSV functionality.
