### ISSUE TITLE
jQuery Missing?

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry-incubator/admin-ui#160]
I'm testing out the latest version and have it running but the web app isn't doing anything because it can't find the jQuery files:

https://admin-ui.sample.url/js/external/jquery/jquery-3.1.1/dist/jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

Looking at the source the files are in fact not there.  Am I missing a step to compile jQuery?  It looks like I'd need to install Node.Js and NPM and run an "npm build" in the jQuery directory to create all the files?  Looking back at the code before you updated to the latest jQuery the JS files were already present in your repo so not sure if this is intentional or not.

**Comment by rboykin** [comment]
@amhuber Thanks for finding this.  

Looks like my commit did not include the jquery files due to a .gitignore in the package.  I've fixed the .gitignore and now the jquery dist are included.

Fixed with commit https://github.com/cloudfoundry-incubator/admin-ui/commit/6c483281abff265183835380c79d4b405b80f529
