### ISSUE TITLE
Used memory and disk in APPS tab

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#176]
Hi,

I'm not getting the data of USED memory and disk under APPS Tab and Spaces TAB. How can i get this information?

![image](https://cloud.githubusercontent.com/assets/12607627/26062527/ae911044-39a8-11e7-85aa-cbc85f89a623.png)

I have few apps under apps tab where its not showing me the buildpack which is binded to that application.

Appreciate your help.

Thanks,
Akhilesh Appana

**Comment by rboykin** [comment]
@Akhilesh-Anb Look in your admin_ui.log.  The app/space/org memory/disk/cpu come from the container metrics which are retrieved from the doppler_logging_endpoint.  If those are not being retrieved due to configuration error, then you will not get those fields.  Also, it can take a bit to get those metrics depending on your doppler_rollup_interval config value.

As for the buildpack missing, if this is not an installed buildpack, the buildpack guid column will be empty.

**Comment by Akhilesh-Anb** [comment]
My log says,


`W, [2017-05-15T16:04:25.017378 #8428]  WARN -- : [ -- ] : [ -- ] : The doppler_logging_endpoint component doppler_logging_endpoint is still not responding`

Can you help me on this. Which configuration i need to check for getting the output.
These are the lines in my config file..

```
doppler_reconnect_delay: 300
doppler_rollup_interval: 30
```

**Comment by rboykin** [comment]
@Akhilesh-Anb See if the firehose plugin works with your cloudfoundry system.  That will determine whether the doppler is correctly configured for your cloudfoundry installation:  https://github.com/cloudfoundry-community/firehose-plugin

If that works, then you can also verify that your admin_ui_client has the authority of doppler_firehose.
