### ISSUE TITLE
Unable to create stats

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#184]
Hi,

I have hosted admin-ui as application. I'm facing few issues

1) Under **stats** tab- When i click on create stats, its throwing me an error like "_**Error saving statistics:
Internal Server Error**_". 

![image](https://user-images.githubusercontent.com/12607627/36052632-848cd42c-0e14-11e8-900d-43d376d9d337.png)

2) Components Tab:- I'm not getting the data into this.
![image](https://user-images.githubusercontent.com/12607627/36054018-33382cb0-0e1a-11e8-8bb6-d5afda3fa3cf.png)

```
[2018-02-09T22:52:18.139713 #44]  WARN -- : [ -- ] : [ -- ] : item_result(http://0.0.0.0:8080/varz): [404 - Page Not Found]
W, [2018-02-09T22:52:18.141531 #44]  WARN -- : [ -- ] : [ -- ] : item_result(http://100.xxx.17.xx:39075/varz): [401 - ]
```

**Note**:- I have followed this to host this as an application (https://github.com/orange-cloudfoundry/admin-ui-configurer)

Appreciate your help/suggestions on this.

Thanks,
Akhilesh Appana

**Comment by rboykin** [comment]
@Akhilesh-Anb I suggest you create an issue against the source github repo for this as opposed to the admin-ui repo. You refer to https://github.com/orange-cloudfoundry/admin-ui-configurer and that has not been updated with a release since Jun 22, 2017 indicating it is very downlevel.

You might also refer to this prior issue regarding running the admin ui as a CF application: https://github.com/cloudfoundry-incubator/admin-ui/issues/145

Lastly, the logs created by your pushed application should indicate where the admin-ui is failing.

**Comment by rboykin** [comment]
@Akhilesh-Anb I just ran the latest admin ui as a CF app on a bosh-lite deployment of cf-deployment. I did the following on top of the standard instructions in the readme to get it to work:
-  Update config/default.yml. This includes the ccdb_uri, cloud_controller_uri, mbus and uaadb_uri
- Modify lib/admin/config.rb to return the port as ENV['PORT'] || @config[:port]
- Create a security group to allow the admin ui to access the various other bosh vms. Strictly for testing, I enabled a case for all ip's and all ports and assigned it as a default running security group
- Modify the admin_ui_client redirect_uri to include the pushed app's URL. I included https://adminui.bosh-lite.com
- Push the app. I pushed with cf push adminui -c "ruby bin/admin"
- You hit the admin ui similarly to any other app: https://adminui.bosh-lite.com 

Realize the stats won't be persisted across restarts since the sqlite DB is created local to the application. I didn't try to tie this in to a separate service.

**Comment by Akhilesh-Anb** [comment]
Hi rboykin,

Thank you so much for the explanation and your response on this.
Could you please help me to understand more on 2nd point.

Appreciate your help on this!

Thanks,
Akhilesh Appana

**Comment by rboykin** [comment]
@Akhilesh-Anb Within the admin ui code itself, there is the file lib/admin/config.rb. That code does not currently handle using the CF app port for execution as a CF app. After cloning the admin-ui, you have to modify that code, specifically here: https://github.com/cloudfoundry-incubator/admin-ui/blob/master/lib/admin/config.rb#L273

**Comment by rboykin** [comment]
@Akhilesh-Anb I'll add that specific logic in point two to the base code and update the admin ui repo. Give me a bit since I will need to go through a test cycle.

**Comment by rboykin** [comment]
@Akhilesh-Anb Added commit so you no longer have to adapt for point two: https://github.com/cloudfoundry-incubator/admin-ui/commit/0f56d5628926356ac9545359e765b945bbc54126
