### ISSUE TITLE
nats-tls support

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry-incubator/admin-ui#192]
Any chance we could get support for NATS-TLS?  It looks like the gem already has support for it, we would just need a way to pass the TLS config options during the connection.

**Comment by rboykin** [comment]
@jmprice I assume you mean the `user_credentials` and/or `nkeys_seed` found here: https://github.com/nats-io/nats.rb/releases/tag/v0.11.0

**Comment by amhuber** [comment]
No, this is about connecting to the new nats-tls job in cf-deployment (https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L388-L410).  CF is moving all the clients over from the legacy nats job on 4222 to the nats-tls job on 4224 and will eventually shut off the non-secure endpoint.  We want to have support for the secure endpoint in admin-ui so we're ready for that, and also because once we have all the non-secure endpoints gone we can finally shut off IPSec.

I've tested the ruby nats client connecting to the CF nats-tls job with the following code, so I think we just need to pass in the "tls" config block when connecting along with the client cert/key and CA cert.

    #!/usr/bin/env ruby
    
    require "nats/client"
    
    options = {
      :servers => [
       'nats://nats:password@10.10.10.10:4224'
      ],
      :max_reconnect_attempts => 10,
      :reconnect_time_wait => 2,
      :tls => {
        :private_key_file => './key.pem',
        :cert_chain_file  => './cert.pem',
        :verify_peer => true,
        :ca_file => './ca.pem'
      }
    }
    
    NATS.on_error do |e|
    puts "Error: #{e}"
    end
    
    NATS.on_disconnect do |reason|
    puts "Disconnected: #{reason}"
    end
    
    NATS.on_reconnect do |nats|
    puts "Reconnected to NATS server at #{nats.connected_server}"
    end
    
    NATS.on_close do
    puts "Connection to NATS closed"
    EM.stop
    end
    
    NATS.start(options) do |nats|
      puts "Connected to NATS at #{nats.connected_server}"
    
      nats.flush do
        nats.publish("hello", "world")
      end
    end

**Comment by rboykin** [comment]
@amhuber Thanks for the specific detail. Hopefully I will get to supporting this week.

**Comment by rboykin** [comment]
@jmprice @amhuber 

Support added with commit https://github.com/cloudfoundry-incubator/admin-ui/commit/68f88e116926c4c8ca17419b8bc8829a0fe3760d

**Comment by amhuber** [comment]
Tested and working great, thanks!

**Comment by jmprice** [comment]
Thank you very much, so fast!  Now if we can just get the remaining components in cf-deployment to do the same...
